# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b0e5c59c91bb13e7c1692ac30a6d8f3fdd7c0e9dba7f5e70cd441e7594daa2cd583eb2ed83b3753fd273abdf9afcecf1229e7e5a011d9114f8d6d7e24d7dd15

test:
  secret_key_base: ffa4b5b5d87052f4a6d59414d4225dbf87d1e8797a41b47f481f5c72ee06efe05ceb61f616f37d93ec1b98799f099e5181ac94d77f00bd36ed2f2c2db60b4524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
